name: Publish to NPM

on:
  release:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Start DynamoDB
        uses: lekki/dynamodb-local-action@v0.1
        with:
          host_port: 8000 # Optional, default value is 8000. The port of host
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
